### ISSUE TITLE
Fails with Spring Music sample app.

### ISSUE THREAD

**Issue by evandbrown** [cloudfoundry/spring-auto-reconfiguration-cnb#4]
I'm trying to push the [Spring Music sample app](https://github.com/cloudfoundry-samples/spring-music). The `cloudfoundry/cnb:bionic` builder applies this buildpack (in addition to the other obvious ones), but the jar it applies appears to be incompatible with the version of Spring Boot in the sample app. I verified this by running `pack` locally, including the buildpacks that detect on the builder, but excluding this buildpack, and it worked.

My first hunch was to look for an env var to disable (like the `JBP_CONFIG_?` one that I think exists for older buildpacks), but that's not in [detect/main.go](https://github.com/cloudfoundry/spring-auto-reconfiguration-cnb/blob/master/detect/main.go). Worth adding? Or is there a simpler way to do this other than creating a brand new buildpack builder that excludes this buildpack?

Thanks!

**Comment by nebhale** [comment]
Argh....  The problem is that there was a bug in Boot where a bunch of the [Boot metadata that we expected isn't there](https://github.com/spring-projects/spring-boot/issues/16068).  This means that we can't properly add things to the Boot classpath (seems like it's isolated to 2.0.0 to 2.0.9).

I've updated Spring Music with a newer version of Boot (and did the upgrade to make it run on Java 11 while I was there), so it should work now.
